### ISSUE TITLE
Feature request: remove trailing whitespaces on save

### ISSUE THREAD

**Issue by resetnow** [mballance/sveditor#357]
Hello,

it would be really useful to have an option to remove trailing whitespaces automatically on save, like Eclipse CDT does. Many HDL editors (like one in Vivado/ISE) are missing this feature.

**Comment by stevenaz** [comment]
Copied feature request to Sourceforge feature requests:
https://sourceforge.net/p/sveditor/feature-requests/126/

**Comment by stevenaz** [comment]
Added in 2.0.0.

**Comment by resetnow** [comment]
Thank you!
